-- 07_group_by.sql
-- SQL Practice: GROUP BY Clause
-- Repository: SQL-Practice
-- Author: Sayed Ahmed Sami

-------------------------------------------------
-- Mini Dataset Reminder
-------------------------------------------------
-- customers: id, name, age, country, city, join_date
-- orders: order_id, customer_id, total_amount, order_date

-------------------------------------------------
-- 1️⃣ Basic GROUP BY
-------------------------------------------------
-- Count number of customers in each country

SELECT country, COUNT(*) AS total_customers
FROM customers
GROUP BY country;


-------------------------------------------------
-- 2️⃣ GROUP BY with SUM
-------------------------------------------------
-- Total order amount per customer

SELECT customer_id, SUM(total_amount) AS total_spent
FROM orders
GROUP BY customer_id;


-------------------------------------------------
-- 3️⃣ GROUP BY with AVG
-------------------------------------------------
-- Average order value per customer

SELECT customer_id, AVG(total_amount) AS avg_order_value
FROM orders
GROUP BY customer_id;


-------------------------------------------------
-- 4️⃣ GROUP BY with multiple columns
-------------------------------------------------
-- Count customers by country and city

SELECT country, city, COUNT(*) AS total_people
FROM customers
GROUP BY country, city;


-------------------------------------------------
-- 5️⃣ GROUP BY with ORDER BY
-------------------------------------------------
-- Countries with the most customers

SELECT country, COUNT(*) AS total_customers
FROM customers
GROUP BY country
ORDER BY total_customers DESC;


-------------------------------------------------
-- 6️⃣ Real World Example
-------------------------------------------------
-- Suppose an e-commerce company wants to know
-- total revenue generated by each customer.

SELECT customer_id, SUM(total_amount) AS revenue
FROM orders
GROUP BY customer_id;