-- 07_group_by.sql
-- SQL Practice: GROUP BY Clause
-- Repository: SQL-Practice
-- Author: Sayed Ahmed Sami

-------------------------------------------------
-- Mini Dataset Reminder
-------------------------------------------------
-- customers: id, name, age, country, city, join_date
-- orders: order_id, customer_id, total_amount, order_date

-------------------------------------------------
-- 1️⃣ Basic GROUP BY
-------------------------------------------------
-- Count number of customers in each country

SELECT country, COUNT(*) AS total_customers
FROM customers
GROUP BY country;


-------------------------------------------------
-- 2️⃣ GROUP BY with SUM
-------------------------------------------------
-- Total order amount per customer

SELECT customer_id, SUM(total_amount) AS total_spent
FROM orders
GROUP BY customer_id;


-------------------------------------------------
-- 3️⃣ GROUP BY with AVG
-------------------------------------------------
-- Average order value per customer

SELECT customer_id, AVG(total_amount) AS avg_order_value
FROM orders
GROUP BY customer_id;


-------------------------------------------------
-- 4️⃣ GROUP BY with multiple columns
-------------------------------------------------
-- Count customers by country and city

SELECT country, city, COUNT(*) AS total_people
FROM customers
GROUP BY country, city;


-------------------------------------------------
-- 5️⃣ GROUP BY with ORDER BY
-------------------------------------------------
-- Countries with the most customers

SELECT country, COUNT(*) AS total_customers
FROM customers
GROUP BY country
ORDER BY total_customers DESC;


-------------------------------------------------
-- 6️⃣ Real World Example
-------------------------------------------------
-- Suppose an e-commerce company wants to know
-- total revenue generated by each customer.

SELECT customer_id, SUM(total_amount) AS revenue
FROM orders
GROUP BY customer_id;



--Corporate HQ is conducting a study on the relationship between replacement cost and a movie MPAA rating(e.g G,PG,R,etc...)
--What is the average replacement cost per MPAA rating ?

SELECT rating,ROUND(AVG(replacement_cost),3) FROM film
GROUP BY rating
ORDER BY ROUND(AVG(replacement_cost),3) DESC;



--We aer running a promotion to reward our top 5 customers with coupons
--What are the customer ids of the top 5 customers by total spend?
SELECT customer_id,SUM(amount) FROM payment
GROUP BY customer_id
ORDER BY SUM(amount) DESC
LIMIT 5;


--WE have two  staff members,with staff IDS 1 and 2. WE want to give bonus to the 
--staff member that handled the most payments
--How many payments did each staff member handle and who gets the bonus?
SELECT staff_id,COUNT(amount) FROM payment
GROUP BY staff_id
ORDER BY COUNT(amount) DESC;